name: monitor_local_notification_example
description: "Example app for monitor_local_notification."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  http_parser: ^4.1.2
  monitor: ^1.1.1
  monitor_http: ^1.0.0
  monitor_local_notification:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
